### ISSUE TITLE
client.member.all - HTTP Error 404

### ISSUE THREAD

**Issue by ucola** [charlesthk/python-mailchimp#54]
We became this error on client.member.all call, any idea?

`
Traceback (most recent call last):
  File "./mailchimp_sync.py", line 8, in <module>
    print client.member.all('1234')
  File "/scripts/mailchimp3/entities/member.py", line 17, in all
    return self._mc_client._get(url=self._build_path(list_id, 'members'), **queryparams)
  File "/scripts/mailchimp3/mailchimpclient.py", line 25, in wrapper
    return fn(self, *args, **kwargs)
  File "/scripts/mailchimp3/mailchimpclient.py", line 76, in _get
    r.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
`

**Comment by ucola** [comment]
MailChimp was having problems with the api, now it works
